name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Publish!
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
